; Default config file for pylama

; PyLint and pydocstyle can't determine private modules
;   C0111 = Missing docstring
;   D100  = Missing docstring in public module

; Pointless or conflicting
;   D203  = 1 blank line required before class docstring
;   D213  = Multi-line docstring summary should start at the second line
;   I0011 = Locally disabling...
;   W0142 = Used * or ** magic
;   W0403 = Relative imports

; For further information consult:
; http://pylint-messages.wikidot.com/messages
; http://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes
; http://pep257.readthedocs.io/en/latest/error_codes.html
; http://flake8.pycqa.org/en/latest/user/error-codes.html

[pylama]
linters = mccabe,pycodestyle,pyflakes,pydocstyle,pylint
ignore = C0111,D100,D203,D213,F0401,I0011,W0142,W0403

[pylama:mccabe]
complexity = 10

[pylama:pylint]
good-names = e
